### ISSUE TITLE
xcode 9.2 build fails

### ISSUE THREAD

**Issue by tamaskenez** [calmopyrin/yapesdl#2] opened 2018-03-04 20:30 UTC
Hi,
Trying to build yapesdl with the xcodeproj file.
I'm having a linker error for a few Cia methods (occuring in vic2mem).
I thought I'd check out the warnings before going after the linker error. I found these repeatedly:

    instantiation of variable 'LinkedList<Resettable>::count' required here, but no definition is available

(also for `root` and `last`)
So, how come those members of `LinkedList` are `static`, is it intentional? One global list per type? Can I ignore this warning? Thanks!

**Comment by calmopyrin** [comment] 2018-04-05 22:46
Hi,

yep those 'static'-s are intentional and the warning leads to the linker error. I guess the problem is that the newly factored out CIA code source file should be added to the project file. Alas, I can not build under Mac but feel free to contribute whatever fix you deem appropriate. 

thanks
Attila

**Comment by calmopyrin** [comment] 2019-06-22 20:18
Fix committed.

**Closed as completed by calmopyrin** 2019-06-22 20:18 UTC
